language: python
python:
  - "3.6"

env:
  - DJANGO_VERSION=3.2.6

services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - python3 manage.py test && flake8 --ignore=E501,W503,E101,W191