# Generated by Django 3.2.6 on 2021-10-14 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.CharField(max_length=128, unique=True)),
                ('nickname', models.CharField(max_length=128, null=True)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('apellido', models.CharField(max_length=128, null=True)),
                ('segundo_apellido', models.CharField(max_length=128, null=True)),
                ('celular', models.CharField(max_length=128, null=True)),
                ('cargo', models.CharField(max_length=128, null=True)),
                ('telefono', models.CharField(max_length=128, null=True)),
                ('notificaciones', models.IntegerField(null=True)),
                ('orden_compra', models.IntegerField(null=True)),
                ('session_key', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airfreight_charges',
            fields=[
                ('origin_airport', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=128, null=True)),
                ('freight_min', models.FloatField(null=True)),
                ('freight_less_45', models.FloatField(null=True)),
                ('freight_45_100', models.FloatField(null=True)),
                ('freight_100_300', models.FloatField(null=True)),
                ('freight_300_500', models.FloatField(null=True)),
                ('freight_500_1000', models.FloatField(null=True)),
                ('freight_more_1000', models.FloatField(null=True)),
                ('fuel_surcharge_min', models.FloatField(null=True)),
                ('fuel_surcharge_kg', models.FloatField(null=True)),
                ('security_surcharge_min', models.FloatField(null=True)),
                ('security_surcharge_kg', models.FloatField(null=True)),
                ('cargo_screening_fee_min', models.FloatField(null=True)),
                ('cargo_screening_fee_kg', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('descripción', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion_Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('correo', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=128, null=True)),
                ('nombre', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correlativo_cotizacion',
            fields=[
                ('año', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Correlativo_orden_compra',
            fields=[
                ('año', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Correlativo_producto',
            fields=[
                ('producto', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('orden_compra', models.BooleanField(null=True)),
                ('fecha_salida', models.DateField(null=True)),
                ('fecha_respuesta', models.DateField(null=True)),
                ('fecha_actualizacion_precio', models.DateField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=128, null=True)),
                ('contacto_asociado', models.ManyToManyField(related_name='contacto_asociado', to='planificador.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Destination_charges',
            fields=[
                ('origin_airport', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=128, null=True)),
                ('terminal_handling', models.FloatField(null=True)),
                ('doc_fee_min', models.FloatField(null=True)),
                ('doc_fee_max', models.FloatField(null=True)),
                ('doc_fee_kg', models.FloatField(null=True)),
                ('desconsolidation', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DHL',
            fields=[
                ('origin_airport', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('priority', models.CharField(max_length=128, null=True)),
                ('airline', models.CharField(max_length=128, null=True)),
                ('direct_flight', models.CharField(max_length=128, null=True)),
                ('departure_days', models.CharField(max_length=128, null=True)),
                ('transit_time', models.CharField(max_length=128, null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_charges', to='planificador.destination_charges')),
                ('freight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_charges', to='planificador.airfreight_charges')),
            ],
        ),
        migrations.CreateModel(
            name='Filtro_producto',
            fields=[
                ('nombre_producto', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=128)),
                ('id_producto', models.CharField(max_length=128, null=True)),
                ('nombre_subclase', models.CharField(max_length=128)),
                ('utilizado', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos_generales',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('numero_factura', models.CharField(max_length=128, null=True)),
                ('factura_o_boleta', models.CharField(max_length=128, null=True)),
                ('razon_social', models.CharField(max_length=128, null=True)),
                ('detalle', models.CharField(max_length=128, null=True)),
                ('monto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Origin_charges',
            fields=[
                ('origin_airport', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=128, null=True)),
                ('pickup_min', models.FloatField(null=True)),
                ('pickup_kg', models.FloatField(null=True)),
                ('handling', models.FloatField(null=True)),
                ('customs_clearence', models.FloatField(null=True)),
                ('other_fees1_description', models.CharField(max_length=128, null=True)),
                ('other_fees1_value_min', models.FloatField(null=True)),
                ('other_fees1_value_kg', models.FloatField(null=True)),
                ('other_fees2_description', models.CharField(max_length=128, null=True)),
                ('other_fees2_value_min', models.FloatField(null=True)),
                ('other_fees2_value_kg', models.FloatField(null=True)),
                ('origin_transit_time', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('planilla', models.FileField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('valor_importación', models.FloatField(null=True)),
                ('tipo_cambio', models.CharField(default='CLP', max_length=128)),
                ('valor_cambio', models.FloatField(null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('nombre_proveedor', models.CharField(max_length=128, null=True)),
                ('nombre_cotizacion', models.CharField(max_length=128, null=True)),
                ('nombre_importacion', models.CharField(max_length=128, null=True)),
                ('comentarios', models.TextField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto_subclases',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('valor', models.FloatField(null=True)),
                ('utilidad', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=512)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('unidad', models.CharField(max_length=128, null=True)),
                ('kilos', models.FloatField(null=True)),
                ('proveedor_interno', models.CharField(max_length=128, null=True)),
                ('imagen', models.ManyToManyField(to='planificador.ImagenProducto')),
                ('lista_precios', models.ManyToManyField(to='planificador.Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_proyecto',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Urgente', 'Urgente'), ('Futuro', 'Futuro')], default='Futuro', max_length=128)),
                ('estado_cotizacion', models.CharField(max_length=128, null=True)),
                ('estado_tiempo', models.CharField(max_length=128, null=True)),
                ('fecha_uso', models.DateField(null=True)),
                ('cantidades', models.FloatField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RMC',
            fields=[
                ('rut', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('giro', models.CharField(max_length=128, null=True)),
                ('direccion', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubClase',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('utilidad', models.FloatField(null=True)),
                ('productos', models.ManyToManyField(to='planificador.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_gastos',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('numero_relacion', models.CharField(max_length=128, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('periodo_desde', models.DateTimeField(null=True)),
                ('periodo_hasta', models.DateTimeField(null=True)),
                ('rut_solicitante', models.CharField(max_length=128, null=True)),
                ('rut_autorizador', models.CharField(max_length=128, null=True)),
                ('rut_aprobador', models.CharField(max_length=128, null=True)),
                ('total_boleta', models.IntegerField(null=True)),
                ('total_factura', models.IntegerField(null=True)),
                ('gastos_generales', models.ManyToManyField(to='planificador.Gastos_generales')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('precio_final', models.FloatField(null=True)),
                ('centro_costos', models.CharField(max_length=128, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_final', models.DateField(null=True)),
                ('creador', models.CharField(max_length=128)),
                ('tipo_cambio', models.CharField(default='CLP', max_length=128, null=True)),
                ('valor_cambio', models.FloatField(default=1, null=True)),
                ('estado', models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto')], default='Incompleto', max_length=128, null=True)),
                ('presupuesto_total', models.FloatField(null=True)),
                ('consolidacion', models.BooleanField(default=False, null=True)),
                ('presupuesto_subclases', models.ManyToManyField(to='planificador.Presupuesto_subclases')),
                ('productos', models.ManyToManyField(through='planificador.Producto_proyecto', to='planificador.Producto')),
                ('relacion_gastos', models.ManyToManyField(to='planificador.Relacion_gastos')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('razon_social', models.CharField(max_length=128, null=True)),
                ('idioma', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], default='ES', max_length=128, null=True)),
                ('direccion', models.CharField(max_length=256, null=True)),
                ('calificaciones', models.ManyToManyField(through='planificador.Calificacion_Proveedor', to='planificador.Calificacion')),
                ('contactos_asociados', models.ManyToManyField(to='planificador.Contacto')),
                ('productos_no', models.ManyToManyField(to='planificador.Producto')),
                ('subclases_asociadas', models.ManyToManyField(to='planificador.SubClase')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_proyecto_cantidades',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('cantidades', models.CharField(max_length=128, null=True)),
                ('precio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precio', to='planificador.precio')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='planificador.producto')),
                ('producto_asociado_cantidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_asociado_cantidades', to='planificador.producto_proyecto')),
                ('proyecto_asociado_cantidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_asociado_cantidades', to='planificador.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='producto_proyecto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.proyecto'),
        ),
        migrations.AddField(
            model_name='producto_proyecto',
            name='proveedores',
            field=models.ManyToManyField(to='planificador.Proveedor'),
        ),
        migrations.AddField(
            model_name='producto_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.producto'),
        ),
        migrations.CreateModel(
            name='Producto_proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_RMC', models.CharField(max_length=128)),
                ('nombre_proveedor', models.CharField(max_length=128)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.proveedor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.producto')),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto_subclases',
            name='subclase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclase', to='planificador.subclase'),
        ),
        migrations.CreateModel(
            name='Permisos_notificacion',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_compra',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('condicion_entrega', models.CharField(max_length=128, null=True)),
                ('condiciones_pago', models.CharField(max_length=128, null=True)),
                ('status_llegada', models.CharField(max_length=128, null=True)),
                ('status_financiero', models.CharField(max_length=128, null=True)),
                ('forma_pago', models.CharField(max_length=128, null=True)),
                ('observaciones', models.TextField(null=True)),
                ('planilla', models.FileField(max_length=255, null=True, upload_to='img')),
                ('fecha_envio', models.DateField(null=True)),
                ('cotizacion_hija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_hija', to='planificador.cotizacion')),
                ('cotizacion_padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_padre', to='planificador.cotizacion')),
                ('destino_factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino_factura', to='planificador.rmc')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=128, null=True)),
                ('accion', models.CharField(max_length=128, null=True)),
                ('modelo_base_datos', models.CharField(max_length=128, null=True)),
                ('numero_modificado', models.IntegerField(null=True)),
                ('id_modelo', models.CharField(max_length=128, null=True)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('id_proyecto', models.CharField(max_length=128, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Importaciones',
            fields=[
                ('codigo', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('codigo_referencial', models.CharField(max_length=128, null=True)),
                ('origen', models.CharField(max_length=128, null=True)),
                ('transporte', models.CharField(max_length=128, null=True)),
                ('kilos', models.FloatField(null=True)),
                ('valor_flete', models.FloatField(null=True)),
                ('valor_origen', models.FloatField(null=True)),
                ('valor_destino', models.FloatField(null=True)),
                ('gastos_despacho', models.FloatField(null=True)),
                ('honorarios', models.FloatField(null=True)),
                ('moneda_importacion', models.CharField(max_length=128, null=True)),
                ('valor_moneda_importacion', models.FloatField(null=True)),
                ('valor_dolar', models.FloatField(null=True)),
                ('UF', models.FloatField(null=True)),
                ('advalorem', models.FloatField(null=True)),
                ('costo_producto', models.FloatField(null=True)),
                ('fecha_emision', models.DateField(null=True)),
                ('fecha_llegada', models.DateField(null=True)),
                ('DHL_asociado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhl', to='planificador.dhl')),
                ('productos', models.ManyToManyField(related_name='productos_importacion', to='planificador.Producto_proyecto_cantidades')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificador.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='dhl',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_charges', to='planificador.origin_charges'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='productos_asociados',
            field=models.ManyToManyField(related_name='productos_asociados', to='planificador.Producto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='productos_proyecto_asociados',
            field=models.ManyToManyField(null=True, related_name='productos_proyecto_asociados', to='planificador.Producto_proyecto_cantidades'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='proveedor_asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_asociado', to='planificador.proveedor'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='proyecto_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_asociado', to='planificador.proyecto'),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('subclases', models.ManyToManyField(to='planificador.SubClase')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion_proveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.proveedor'),
        ),
        migrations.AddField(
            model_name='user',
            name='cotizaciones',
            field=models.ManyToManyField(to='planificador.Cotizacion'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='precios',
            field=models.ManyToManyField(to='planificador.Precio'),
        ),
        migrations.AddField(
            model_name='user',
            name='productos_proyecto',
            field=models.ManyToManyField(to='planificador.Producto_proyecto'),
        ),
        migrations.AddField(
            model_name='user',
            name='proyectos',
            field=models.ManyToManyField(to='planificador.Proyecto'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
