# Generated by Django 2.1.1 on 2021-03-11 20:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('lista_precios', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None)),
                ('fecha_actualizacion', models.DateField(null=True)),
                ('clase', models.CharField(max_length=128)),
                ('subclase', models.CharField(max_length=128)),
                ('unidad', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UR', 'Urgente'), ('TR', 'Transporte'), ('BO', 'Bodega'), ('FU', 'Futuro')], default='FU', max_length=2)),
                ('fecha_uso', models.DateField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=128, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('razon_social', models.CharField(max_length=128, null=True)),
                ('clases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, null=True), size=None)),
                ('subclases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('precio_final', models.FloatField(null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_final', models.DateField(null=True)),
                ('administrador_contrato', models.CharField(max_length=128, null=True)),
                ('creador', models.CharField(max_length=128)),
                ('productos', models.ManyToManyField(through='planificador.Producto_proyecto', to='planificador.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.Proyecto'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='proveedor',
            field=models.ManyToManyField(to='planificador.Proveedor'),
        ),
    ]
