# Generated by Django 2.1.1 on 2021-03-11 20:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="lista_precios",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(null=True), null=True, size=None
            ),
        ),
    ]
