# Generated by Django 3.2.6 on 2021-11-18 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion_DHL',
            fields=[
                ('codigo', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=128, null=True)),
                ('carga_peligrosa', models.CharField(max_length=128, null=True)),
                ('invoice', models.FileField(max_length=255, null=True, upload_to='img')),
                ('info', models.FileField(max_length=255, null=True, upload_to='img')),
                ('dgd', models.FileField(max_length=255, null=True, upload_to='img')),
                ('msds', models.FileField(max_length=255, null=True, upload_to='img')),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
