# Generated by Django 2.1.1 on 2021-03-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0002_auto_20210311_2015"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="ultimo_proveedor",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
