# Generated by Django 3.2.6 on 2021-11-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0002_cotizacion_dhl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion_dhl',
            name='fecha_enviada',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_dhl',
            name='fecha_llegada',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_dhl',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
    ]
