# Generated by Django 3.2.6 on 2021-12-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0003_auto_20211122_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('formula', models.CharField(max_length=128, null=True)),
                ('entero', models.BooleanField(default=False)),
                ('valor', models.FloatField(null=True)),
                ('producto_calculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_calculo', to='planificador.producto')),
            ],
        ),
    ]
