# Generated by Django 3.2.6 on 2021-10-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto_asociado',
            field=models.ManyToManyField(null=True, related_name='contacto_asociado', to='planificador.Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='calificaciones',
            field=models.ManyToManyField(null=True, through='planificador.Calificacion_Proveedor', to='planificador.Calificacion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contactos_asociados',
            field=models.ManyToManyField(null=True, to='planificador.Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='productos_no',
            field=models.ManyToManyField(null=True, to='planificador.Producto'),
        ),
    ]
