# Generated by Django 3.2.6 on 2021-12-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0004_calculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('abreviacion', models.CharField(max_length=128, null=True)),
                ('valor', models.FloatField(null=True)),
                ('unidad', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
