# Generated by Django 3.2.6 on 2021-12-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0005_atributo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRiesgo',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=128, null=True)),
                ('calculos', models.ManyToManyField(related_name='calculos', to='planificador.Calculo')),
            ],
        ),
        migrations.CreateModel(
            name='Restricciones',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('operador', models.CharField(max_length=128, null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('atributo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributo', to='planificador.atributo')),
            ],
        ),
        migrations.CreateModel(
            name='InstalacionProyecto',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=128, null=True)),
                ('fecha_creacion', models.DateField(null=True)),
                ('productos_asociados', models.ManyToManyField(related_name='productos_proyecto', to='planificador.Producto_proyecto_cantidades')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='planificador.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('nombre', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('atributos', models.ManyToManyField(related_name='atributos', to='planificador.Atributo')),
                ('control_riesgo', models.ManyToManyField(related_name='controlriesgo', to='planificador.ControlRiesgo')),
            ],
        ),
        migrations.AddField(
            model_name='controlriesgo',
            name='restricciones',
            field=models.ManyToManyField(related_name='restricciones', to='planificador.Restricciones'),
        ),
    ]
