# Generated by Django 3.2.6 on 2021-12-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0006_auto_20211215_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculo',
            name='producto_calculo',
        ),
        migrations.AddField(
            model_name='calculo',
            name='producto_calculo',
            field=models.ManyToManyField(related_name='producto_calculo', to='planificador.Producto'),
        ),
    ]
