# Generated by Django 3.2.6 on 2021-12-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0007_auto_20211215_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalaciones',
            name='atributos',
        ),
        migrations.AddField(
            model_name='instalacionproyecto',
            name='instalacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='planificador.instalaciones'),
        ),
    ]
