# Generated by Django 2.1.1 on 2021-03-12 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0008_producto_lista_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='lista_tipo_cambio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, null=True), default=list, size=None),
        ),
    ]
