# Generated by Django 3.2.6 on 2022-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0009_restricciones_calculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacionproyecto',
            name='controles_riesgo',
            field=models.ManyToManyField(related_name='control_riesgos', to='planificador.ControlRiesgo'),
        ),
    ]
