# Generated by Django 3.2.6 on 2022-01-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0010_instalacionproyecto_controles_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='d1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='d2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='hh1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='hh2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='hh3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='hh4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='hh5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='hh6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='hh7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='hh8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='perimetro',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='superficie',
            field=models.FloatField(null=True),
        ),
    ]
