# Generated by Django 3.2.6 on 2022-01-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0011_auto_20220125_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='d1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='d2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
