# Generated by Django 2.1.1 on 2021-03-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0012_auto_20210312_1903"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacto",
            old_name="nombre",
            new_name="nombre_contacto",
        ),
    ]
