# Generated by Django 2.1.1 on 2021-03-15 13:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0013_auto_20210312_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='lista_contactos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
