# Generated by Django 2.1.1 on 2021-03-15 16:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0015_auto_20210315_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='lista_calificaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), default=list, size=None),
        ),
    ]
