# Generated by Django 2.1.1 on 2021-03-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0017_auto_20210315_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('fecha_actualizacion', models.DateField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('tipo_cambio', models.CharField(default='CLP', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lista_precios',
        ),
        migrations.AlterField(
            model_name='producto_proyecto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.Proyecto'),
        ),
        migrations.AlterField(
            model_name='producto_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='lista_precios',
            field=models.ManyToManyField(to='planificador.Precio'),
        ),
    ]
