# Generated by Django 2.1.1 on 2021-03-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0018_auto_20210315_2055"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="fechas_actualizaciones_historicas",
        ),
    ]
