# Generated by Django 2.1.1 on 2021-03-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0019_remove_producto_fechas_actualizaciones_historicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='nombre_proveedor',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
