# Generated by Django 2.1.1 on 2021-03-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0023_auto_20210316_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_proyecto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.Proyecto'),
        ),
    ]
