# Generated by Django 2.1.1 on 2021-03-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0024_auto_20210316_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion_proveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.Proveedor', to_field='rut'),
        ),
    ]
