# Generated by Django 2.1.1 on 2021-03-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0027_remove_proyecto_centro_costos'),
    ]

    operations = [
     
    ]
