# Generated by Django 2.1.1 on 2021-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0028_remove_proyecto_centro_costos'),
    ]

    operations = [
        
    ]
