# Generated by Django 2.1.1 on 2021-03-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0029_proyecto_centro_costos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='centro_costos',
        ),
    ]
