# Generated by Django 2.1.1 on 2021-03-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0030_remove_proyecto_centro_costos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clase",
            name="subclases",
            field=models.ManyToManyField(null=True, to="planificador.SubClase"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="lista_precios",
            field=models.ManyToManyField(null=True, to="planificador.Precio"),
        ),
        migrations.AlterField(
            model_name="subclase",
            name="productos",
            field=models.ManyToManyField(null=True, to="planificador.Producto"),
        ),
    ]
