# Generated by Django 2.1.1 on 2021-03-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0034_auto_20210316_1635"),
    ]

    operations = [
        migrations.RenameField(
            model_name="precio",
            old_name="fecha_creacion",
            new_name="id",
        ),
    ]
