# Generated by Django 2.1.1 on 2021-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0035_auto_20210316_1751'),
    ]

    operations = [
        
    ]
