# Generated by Django 2.1.1 on 2021-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0036_auto_20210316_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='id',
        ),
    ]
