# Generated by Django 2.1.1 on 2021-03-16 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0037_auto_20210316_1757"),
    ]

    operations = []
