# Generated by Django 2.1.1 on 2021-03-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0040_precio_fecha_creacion'),
    ]

    operations = [
        
    ]
