# Generated by Django 2.1.1 on 2021-03-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0041_auto_20210316_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='lista_precios',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
