# Generated by Django 2.1.1 on 2021-03-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0043_auto_20210316_1818"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proveedor",
            old_name="clases_asociadas",
            new_name="subclases_asociadas",
        ),
    ]
