# Generated by Django 2.1.1 on 2021-03-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0045_auto_20210318_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_RMC', models.CharField(max_length=128)),
                ('nombre_proveedor', models.CharField(max_length=128)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='precio',
            name='valor_cambio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='precio',
            name='valor_importación',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='kilos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto_proyecto',
            name='cantidades',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto_proveedor',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificador.Producto'),
        ),
    ]
