# Generated by Django 3.1.7 on 2021-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0054_auto_20210330_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
