# Generated by Django 3.1.7 on 2021-03-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0056_filtro_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField(null=True)),
                ('fecha_respuesta', models.DateField(null=True)),
                ('fecha_actualizacion_precio', models.DateField(null=True)),
                ('usuario_modificacion', models.CharField(max_length=128, null=True)),
                ('productos_asociados', models.ManyToManyField(related_name='productos_asociados', to='planificador.Producto')),
                ('proyecto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_asociado', to='planificador.producto')),
            ],
        ),
    ]
