# Generated by Django 3.1.7 on 2021-03-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0057_cotizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="proveedor_asociado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proveedor_asociado",
                to="planificador.proveedor",
            ),
        ),
    ]
