# Generated by Django 3.1.7 on 2021-03-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0060_cotizacion_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto_proyecto",
            name="id",
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
