# Generated by Django 3.1.7 on 2021-04-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0062_auto_20210401_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='nombre_cotizacion',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
