# Generated by Django 3.1.7 on 2021-04-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0063_precio_nombre_cotizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="precio",
            name="usuario_modificacion",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
