# Generated by Django 3.1.7 on 2021-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0066_auto_20210416_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto_proyecto",
            name="estado_cotizacion",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
