# Generated by Django 3.1.7 on 2021-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0067_producto_proyecto_estado_cotizacion"),
    ]

    operations = []
