# Generated by Django 3.1.7 on 2021-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0070_auto_20210420_1428'),
    ]

    operations = [
        
    ]
