# Generated by Django 3.1.7 on 2021-04-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0072_proyecto_centro_costos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_proyecto',
            name='status',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Futuro', 'Futuro')], default='Futuro', max_length=128),
        ),
    ]
