# Generated by Django 3.1.7 on 2021-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0074_correlativo_cotizacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cotizacion",
            name="contacto_asociado",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="contacto_asociado",
            field=models.ManyToManyField(
                null=True, related_name="contacto_asociado", to="planificador.Contacto"
            ),
        ),
    ]
