# Generated by Django 3.1.7 on 2021-04-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0075_auto_20210422_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="contacto_asociado",
            field=models.ManyToManyField(
                related_name="contacto_asociado", to="planificador.Contacto"
            ),
        ),
    ]
