# Generated by Django 3.1.7 on 2021-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0077_notificacion_permisos_notificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="id_modelo",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="nombre",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="numero_modificado",
            field=models.IntegerField(null=True),
        ),
    ]
