# Generated by Django 3.1.7 on 2021-04-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0078_auto_20210423_1313"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificacion",
            name="tipo_notificacion",
        ),
    ]
