# Generated by Django 3.1.7 on 2021-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0081_remove_notificacion_como"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
