# Generated by Django 3.1.7 on 2021-04-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0082_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
