# Generated by Django 3.1.7 on 2021-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0083_auto_20210423_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificaciones',
            field=models.IntegerField(null=True),
        ),
    ]
