# Generated by Django 3.1.7 on 2021-04-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0084_usuario_notificaciones"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificacion",
            name="usuario_modificacion",
        ),
        migrations.AddField(
            model_name="notificacion",
            name="usuario_modificacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="planificador.usuario",
            ),
        ),
    ]
