# Generated by Django 3.1.7 on 2021-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0086_filtro_producto_id_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precio",
            name="fecha",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=512),
        ),
    ]
