# Generated by Django 3.1.7 on 2021-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0088_producto_proyecto_estado_tiempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo_producto',
            fields=[
                ('producto', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
