# Generated by Django 3.1.7 on 2021-06-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0090_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='session_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
