# Generated by Django 3.1.7 on 2021-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0091_usuario_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
