# Generated by Django 3.1.7 on 2021-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0093_auto_20210623_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro_producto',
            name='utilizado',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
