# Generated by Django 3.1.7 on 2021-06-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0094_filtro_producto_utilizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMC',
            fields=[
                ('rut', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128, null=True)),
                ('giro', models.CharField(max_length=128, null=True)),
                ('direccion', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_compra',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('condicion_entrega', models.CharField(max_length=128, null=True)),
                ('condiciones_pago', models.CharField(max_length=128, null=True)),
                ('status_llegada', models.CharField(max_length=128, null=True)),
                ('status_financiero', models.CharField(max_length=128, null=True)),
                ('forma_pago', models.CharField(max_length=128, null=True)),
                ('observaciones', models.TextField(null=True)),
                ('cotizacion_hija', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_hija', to='planificador.cotizacion')),
                ('cotizacion_padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_padre', to='planificador.cotizacion')),
                ('destino_factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino_factura', to='planificador.cotizacion')),
            ],
        ),
    ]
