# Generated by Django 3.1.7 on 2021-06-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0098_auto_20210630_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correlativo_orden_compra',
        ),
    ]
