# Generated by Django 3.1.7 on 2021-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0099_delete_correlativo_orden_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="orden_compra",
            field=models.IntegerField(null=True),
        ),
    ]
