# Generated by Django 3.1.7 on 2021-07-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0101_orden_compra_planilla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden_compra",
            name="planilla",
            field=models.FileField(max_length=255, null=True, upload_to="img"),
        ),
    ]
