# Generated by Django 3.1.7 on 2021-07-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0102_auto_20210707_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos_generales',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(null=True)),
                ('numero_factura', models.CharField(max_length=128, null=True)),
                ('factura_o_boleta', models.CharField(max_length=128, null=True)),
                ('razon_social', models.CharField(max_length=128, null=True)),
                ('detalle', models.CharField(max_length=128, null=True)),
                ('monto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_gastos',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('numero_relacion', models.CharField(max_length=128, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('periodo_desde', models.DateTimeField(null=True)),
                ('periodo_hasta', models.DateTimeField(null=True)),
                ('rut_solicitante', models.CharField(max_length=128, null=True)),
                ('rut_autorizador', models.CharField(max_length=128, null=True)),
                ('rut_aprobador', models.CharField(max_length=128, null=True)),
                ('total_boleta', models.IntegerField(null=True)),
                ('total_factura', models.IntegerField(null=True)),
                ('gastos_generales', models.ManyToManyField(to='planificador.Gastos_generales')),
            ],
        ),
    ]
