# Generated by Django 3.1.7 on 2021-07-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0103_gastos_generales_relacion_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='relacion_gastos',
            field=models.ManyToManyField(to='planificador.Relacion_gastos'),
        ),
    ]
