# Generated by Django 3.1.7 on 2021-07-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0104_proyecto_relacion_gastos"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto_proyecto_cantidades",
            name="precio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precio",
                to="planificador.precio",
            ),
        ),
    ]
