# Generated by Django 3.1.7 on 2021-07-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0105_producto_proyecto_cantidades_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra',
            name='fecha_envio',
            field=models.DateField(null=True),
        ),
    ]
