# Generated by Django 3.1.7 on 2021-07-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0106_orden_compra_fecha_envio"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="presupuesto_total",
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name="Presupuesto_subclases",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("valor", models.FloatField(null=True)),
                (
                    "subclase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subclase",
                        to="planificador.subclase",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proyecto",
            name="presupuesto_subclases",
            field=models.ManyToManyField(to="planificador.Presupuesto_subclases"),
        ),
    ]
