# Generated by Django 3.1.7 on 2021-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0108_correlativo_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto_subclases',
            name='utilidad',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='subclase',
            name='utilidad',
            field=models.FloatField(null=True),
        ),
    ]
