# Generated by Django 3.1.7 on 2021-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0109_auto_20210728_1411"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="consolidacion",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
