# Generated by Django 3.1.7 on 2021-07-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0111_auto_20210728_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="interno",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
