# Generated by Django 3.1.7 on 2021-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0113_auto_20210729_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='productos_no',
            field=models.ManyToManyField(to='planificador.Producto'),
        ),
    ]
