# Generated by Django 3.1.7 on 2021-08-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0114_proveedor_productos_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airfreight_charges',
            fields=[
                ('origin_airport', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=128, null=True)),
                ('freight_min', models.FloatField(null=True)),
                ('freight_less_45', models.FloatField(null=True)),
                ('freight_45_100', models.FloatField(null=True)),
                ('freight_100_300', models.FloatField(null=True)),
                ('freight_300_500', models.FloatField(null=True)),
                ('freight_500_1000', models.FloatField(null=True)),
                ('freight_more_1000', models.FloatField(null=True)),
                ('fuel_surcharge_min', models.FloatField(null=True)),
                ('fuel_surcharge_kg', models.FloatField(null=True)),
                ('security_surcharge_min', models.FloatField(null=True)),
                ('security_surcharge_kg', models.FloatField(null=True)),
                ('cargo_screening_fee_min', models.FloatField(null=True)),
                ('cargo_screening_fee_kg', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination_charges',
            fields=[
                ('origin_airport', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=128, null=True)),
                ('terminal_handling', models.FloatField(null=True)),
                ('doc_fee_min', models.FloatField(null=True)),
                ('doc_fee_max', models.FloatField(null=True)),
                ('doc_fee_kg', models.FloatField(null=True)),
                ('desconsolidation', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DHL',
            fields=[
                ('origin_airport', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('airline', models.CharField(max_length=128, null=True)),
                ('direct_flight', models.CharField(max_length=128, null=True)),
                ('departure_days', models.FloatField(null=True)),
                ('transit_time', models.FloatField(null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_charges', to='planificador.destination_charges')),
                ('freight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_charges', to='planificador.airfreight_charges')),
            ],
        ),
        migrations.CreateModel(
            name='Origin_charges',
            fields=[
                ('origin_airport', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=128, null=True)),
                ('pickup_min', models.FloatField(null=True)),
                ('pickup_kg', models.FloatField(null=True)),
                ('handling', models.FloatField(null=True)),
                ('customs_clearence', models.FloatField(null=True)),
                ('other_fees1_description', models.CharField(max_length=128, null=True)),
                ('other_fees1_value_min', models.FloatField(null=True)),
                ('other_fees1_value_kg', models.FloatField(null=True)),
                ('other_fees2_description', models.CharField(max_length=128, null=True)),
                ('other_fees2_value_min', models.FloatField(null=True)),
                ('other_fees2_value_kg', models.FloatField(null=True)),
                ('origin_transit_time', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Importaciones',
            fields=[
                ('codigo', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=128, null=True)),
                ('transporte', models.CharField(max_length=128, null=True)),
                ('kilos', models.FloatField(null=True)),
                ('valor_flete', models.FloatField(null=True)),
                ('valor_otros', models.FloatField(null=True)),
                ('moneda_importacion', models.CharField(max_length=128, null=True)),
                ('valor_moneda_importacion', models.FloatField(null=True)),
                ('advalorem', models.FloatField(null=True)),
                ('costo_producto', models.FloatField(null=True)),
                ('fecha_emision', models.DateField(null=True)),
                ('fecha_llegada', models.DateField(null=True)),
                ('DHL_asociado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_charges', to='planificador.dhl')),
                ('productos', models.ManyToManyField(related_name='productos_importacion', to='planificador.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='dhl',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_charges', to='planificador.origin_charges'),
        ),
    ]
