# Generated by Django 3.1.7 on 2021-08-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planificador", "0115_auto_20210823_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dhl",
            name="departure_days",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="dhl",
            name="transit_time",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
