# Generated by Django 3.1.7 on 2021-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0116_auto_20210823_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhl',
            name='priority',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
