# Generated by Django 3.1.7 on 2021-08-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0117_dhl_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importaciones',
            name='DHL_asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhl', to='planificador.dhl'),
        ),
    ]
