# Generated by Django 3.1.7 on 2021-08-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0118_auto_20210823_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importaciones',
            old_name='valor_otros',
            new_name='valor_destino',
        ),
        migrations.AddField(
            model_name='importaciones',
            name='valor_origen',
            field=models.FloatField(null=True),
        ),
    ]
