# Generated by Django 3.1.7 on 2021-08-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0121_auto_20210825_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importaciones',
            name='productos',
            field=models.ManyToManyField(related_name='productos_importacion', to='planificador.Producto_proyecto_cantidades'),
        ),
    ]
