# Generated by Django 3.1.7 on 2021-08-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0122_auto_20210825_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_proyecto_cantidades',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='planificador.producto'),
        ),
    ]
