# Generated by Django 3.1.7 on 2021-08-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0124_auto_20210825_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='importaciones',
            name='valor_dolar',
            field=models.FloatField(null=True),
        ),
    ]
