# Generated by Django 3.1.7 on 2021-08-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0125_importaciones_valor_dolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='importaciones',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planificador.proveedor'),
        ),
    ]
