# Generated by Django 3.2.6 on 2021-09-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0126_importaciones_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='importaciones',
            name='codigo_referencial',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
