# Generated by Django 3.2.6 on 2021-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0128_auto_20210906_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='importaciones',
            name='UF',
            field=models.FloatField(null=True),
        ),
    ]
