# Generated by Django 3.2.6 on 2021-09-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0129_importaciones_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_proyecto_cantidades',
            name='cantidades_anterior',
        ),
    ]
